pubsub:
  project_id: "go-pub-sub-kafka-data-mover"
  subscription_id: "pub-sub-data-mover"

kafka:
  bootstrap_servers: "<your-server-not-mine>"
  security_protocol: "SASL_SSL"
  sasl_mechanisms: "PLAIN"
  sasl_username: "<your-keys-not-mine>"
  sasl_password: "<your-keys-not-mine>"
  topic: "kafka-data-mover"

app:
  name: "pubsub-kafka-bridge"
  log_level: "info"
